fix critical error in enc, bug fix (add basedir in instabot, to start in other locations)

diff --git a/enc b/enc
--- a/enc
+++ b/enc
@@ -7,6 +7,10 @@ if [ $1 == '-n' ]; then
 	read -s pass
 	printf "***\n"
 	openssl aes-128-cbc -e -in $dec -out $enc -k $pass
+	if [ $? -ne 0 ]; then
+		echo "Unnown error"
+		exit 1
+	fi
 	cp $enc $dec
 	rm $enc
 else
@@ -15,8 +19,16 @@ else
 	printf "Введите парольную фразу: "
 	read -s pass
 	printf "***\n"
-	openssl aes-128-cbc -d -in $enc -out $dec -k $pass
-	vi $dec
+	openssl aes-128-cbc -d -in $enc -out $dec -k $pass 2>/dev/null
+	if [ $? -ne 0 ]; then
+		echo "Incorrect password"
+		exit 1
+	fi
+	editor $dec
 	openssl aes-128-cbc -e -in $dec -out $enc -k $pass
+	if [ $? -ne 0 ]; then
+		echo "Unnown error"
+		exit 1
+	fi
 	rm $dec
 fi
